name: kubernetes_manifest acceptance tests
on:
  push:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
  pull_request:
    branches:
      - main
    paths:
      - "manifest/**/*.go"
jobs:
  tf_version_list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: tf_version_list
      shell: bash
      run: scripts/tfversions.sh
    outputs:
      version_matrix: ${{ steps.tf_version_list.outputs.matrix }}
  acceptance_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kubernetes_version:
          - v1.21.2-k3s1
          - v1.20.8-k3s1
          - v1.19.12-k3s1
          - v1.18.2-k3s1
        terraform_version: ${{ fromJson(needs.tf_version_list.outputs.version_matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Read go-version
        id: go-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.go-version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.content }}
      - name: Setup k3s cluster 
        uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: ${{ matrix.kubernetes_version }}
      - name: Build annotations webhook
        run: |
          docker build --rm -t tf-k8s-acc-webhook ./manifest/test/acceptance/testdata/ComputedFields/webhook/
          docker save --output tf-k8s-acc-webhook.tar tf-k8s-acc-webhook
          k3s ctr images import ./tf-k8s-acc-webhook.tar
      - name: Run tests
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform_version }}
        run: |
          KUBE_CONFIG_PATH="${HOME}/.kube/config" go test -count=1 -tags acceptance -v ./manifest/test/acceptance/... -timeout 120m
